# cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'compute'
    - 'instances'
    - 'list'
    - '--project='
    # This flag tells gcloud to use the impersonated account's credentials
    - '--impersonate-service-account=deployment-sa@.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY