# cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'compute'
    - 'instances'
    - 'list'
    - '--project=carbide-pilot-330923'
    # This flag tells gcloud to use the impersonated account's credentials
    - '--impersonate-service-account=deployment-sa@carbide-pilot-330923.iam.gserviceaccount.com'
# Add this options block to specify the logging mode
options:
  logging: CLOUD_LOGGING_ONLY